### ISSUE TITLE
Binding ip to docker network

### ISSUE THREAD

**Issue by darktelco** [lalanza808/docker-monero-node#3]
I have a setup where I have an overlay network in docker that binds to the docker host and lets me share resources (ingress is caddy which is configured properly).  Since the default configuration in this image is `0.0.0.0` it will bind to the local ip address properly but for some reason even trying to reach it outside of the network the wallet will not connect.

I've tried manually knocking on all of the ports and telnet to configure connectivity and it's good, but for whatever reason connecting via the wallet-cli sits there and hangs.

**Comment by darktelco** [comment]
Looking further into this I believe the issue is here:

```
    environment:
      DAEMON_HOST: http://monerod:18083
      PORT: 8080
    ports:
      - 127.0.0.1:8080:8080
  ```

Should this port be expose on an ip address on the given docker overlay network vs the loopback interface ip?
